---
name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Build
        run: bash -x .ci.sh

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/gss_*.uf2
          generate_release_notes: true
          fail_on_unmatched_files: true
